config/routes.rb
Rails.application.routes.draw do
  resources :coupons
  resources :user_card_charge_settings
  resources :prices
  devise_for :workers
  
  resources :workers do 
    member do 
      get :reset_password
      put :change_current_city
    end
  end
  resources :roles

  resources :categories do
    member do 
      get :recover
      get :prices
      post :init_prices
    end
    resources :products do
      member do 
      get :recover
    end
    end
  end

  resources :stations do
  end

  resources :addresses do 
    collection do 
      get :suggestion
    end
  end

  resources :cities

  resources :couriers

  resources :price_rules

  resources :orders do 
  end

  resources :users do 
    resources :user_cards do 
      member do 
        get :charge
        post :charge
      end
    end
    resources :coupons
  end

  resources :coupon_lists do 
    resources :order_promotions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/workers_role.rb
class WorkersRole < ApplicationRecord
end

app/controllers/workers_roles_controller.rb
class WorkersRolesController < ApplicationController
  before_action :set_workers_role, only: [:show, :edit, :update, :destroy]

  # GET /workers_roles
  # GET /workers_roles.json
  def index
    @workers_roles = WorkersRole.all
  end

  # GET /workers_roles/1
  # GET /workers_roles/1.json
  def show
  end

  # GET /workers_roles/new
  def new
    @workers_role = WorkersRole.new
  end

  # GET /workers_roles/1/edit
  def edit
  end

  # POST /workers_roles
  # POST /workers_roles.json
  def create
    @workers_role = WorkersRole.new(workers_role_params)

    respond_to do |format|
      if @workers_role.save
        format.html { redirect_to @workers_role, notice: 'Workers role was successfully created.' }
        format.json { render :show, status: :created, location: @workers_role }
      else
        format.html { render :new }
        format.json { render json: @workers_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers_roles/1
  # PATCH/PUT /workers_roles/1.json
  def update
    respond_to do |format|
      if @workers_role.update(workers_role_params)
        format.html { redirect_to @workers_role, notice: 'Workers role was successfully updated.' }
        format.json { render :show, status: :ok, location: @workers_role }
      else
        format.html { render :edit }
        format.json { render json: @workers_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers_roles/1
  # DELETE /workers_roles/1.json
  def destroy
    @workers_role.destroy
    respond_to do |format|
      format.html { redirect_to workers_roles_url, notice: 'Workers role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workers_role
      @workers_role = WorkersRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workers_role_params
      params.require(:workers_role).permit(:worker_id, :role_id)
    end
end

app/helpers/workers_roles_helper.rb
module WorkersRolesHelper
end

app/views/workers_roles/_form.html.slim
= form_for @workers_role do |f|
  - if @workers_role.errors.any?
    #error_explanation
      h2 = "#{pluralize(@workers_role.errors.count, "error")} prohibited this workers_role from being saved:"
      ul
        - @workers_role.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :worker_id
    = f.number_field :worker_id
  .field
    = f.label :role_id
    = f.number_field :role_id
  .actions = f.submit

app/views/workers_roles/edit.html.slim
h1 Editing workers_role

== render 'form'

=> link_to 'Show', @workers_role
'|
=< link_to 'Back', workers_roles_path

app/views/workers_roles/index.html.slim
h1 Listing workers_roles

table
  thead
    tr
      th Worker
      th Role
      th
      th
      th

  tbody
    - @workers_roles.each do |workers_role|
      tr
        td = workers_role.worker_id
        td = workers_role.role_id
        td = link_to 'Show', workers_role
        td = link_to 'Edit', edit_workers_role_path(workers_role)
        td = link_to 'Destroy', workers_role, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Workers role', new_workers_role_path

app/views/workers_roles/new.html.slim
h1 New workers_role

== render 'form'

= link_to 'Back', workers_roles_path

app/views/workers_roles/show.html.slim
p#notice = notice

p
  strong Worker:
  = @workers_role.worker_id
p
  strong Role:
  = @workers_role.role_id

=> link_to 'Edit', edit_workers_role_path(@workers_role)
'|
=< link_to 'Back', workers_roles_path